services:
  api:
    container_name: nestjs_dev_container
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - 4000:8000
    
    networks:
      - nest-net

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      - NODE_ENV=development

networks:
  nest-net:
    driver: bridge